const fruits = [
    {
        name: "apple",
        price: 2.85,
        family: "Rosaceae",
        vitamin: ["Vitamin B", "Vitamin K"],
        color: ["red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Apples are crisp, juicy fruits from the Rosaceae family. They come in various colors and flavors, ranging from sweet to tart. Apples are often eaten raw, used in baking, and pressed into cider.",
    },
    {
        name: "apricot",
        price: 4.16,
        family: "Rosaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["orange", "red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Apricots are small, orange fruits from the Rosaceae family known for their velvety skin and sweet-tart flavor. They are commonly eaten fresh, dried, or used in jams and desserts.",
    },
    {
        name: "avocado",
        price: 4.02,
        family: "Lauraceae",
        vitamin: ["Vitamin B", "Vitamin C"],
        color: ["yellow"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Avocados are creamy, nutrient-dense fruits from the Lauraceae family. Rich in healthy fats and vitamins, they are often used in salads, spreads, and dips like guacamole.",
    },
    {
        name: "banana",
        price: 3.51,
        family: "Musaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Bananas are elongated, sweet fruits from the Musaceae family. They are a convenient snack, rich in potassium and energy-boosting carbohydrates.",
    },
    {
        name: "blackberry",
        price: 3.12,
        family: "Rosaceae",
        vitamin: ["Vitamin D", "Vitamin A"],
        color: ["yellow"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Blackberries are dark purple to black fruits from the Rosaceae family. They have a sweet-tart flavor and are commonly used in desserts, jams, and smoothies.",
    },
    {
        name: "blueberry",
        price: 1.19,
        family: "Ericaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Blueberries are small, round fruits from the Ericaceae family, known for their sweet flavor and deep blue color. They are rich in antioxidants and widely used in baking and snacks.",
    },
    {
        name: "cherry",
        price: 3.81,
        family: "Rosaceae",
        vitamin: ["Vitamin B", "Vitamin C"],
        color: ["orange", "red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Cherries are small, round fruits with a sweet or tart flavor. Belonging to the Rosaceae family, they are enjoyed fresh, in pies, or preserved as jams.",
    },
    {
        name: "dragon-fruit",
        price: 4.36,
        family: "Cactaceae",
        vitamin: ["Vitamin D", "Vitamin A"],
        color: ["red", "green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Dragon fruit, or pitaya, comes from the cactus family. It has a striking appearance with a spiky skin and sweet, mildly tangy flesh speckled with black seeds.",
    },
    {
        name: "fig",
        price: 3.21,
        family: "Moraceae",
        vitamin: ["Vitamin B", "Vitamin K"],
        color: ["red", "green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Figs are sweet, pear-shaped fruits from the Moraceae family with a soft texture and many tiny seeds. They are eaten fresh, dried, or used in baking and preserves.",
    },
    {
        name: "grape",
        price: 3.36,
        family: "Vitaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Grapes are small, juicy fruits from the Vitaceae family. Available in various colors, they are eaten fresh, dried into raisins, or used to make juice and wine.",
    },
    {
        name: "grapefruit",
        price: 1.32,
        family: "Rutaceae",
        vitamin: ["Vitamin D", "Vitamin A"],
        color: ["yellow", "green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Grapefruits are large, tart citrus fruits from the Rutaceae family. They are enjoyed for their juicy segments and are commonly eaten fresh or juiced.",
    },
    {
        name: "kiwi",
        price: 3.35,
        family: "Actinidiaceae",
        vitamin: ["Vitamin B", "Vitamin K"],
        color: ["orange", "red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Kiwis are small, fuzzy fruits from the Actinidiaceae family. They have bright green or golden flesh with a unique sweet-tart flavor and are rich in vitamin C.",
    },
    {
        name: "lemon",
        price: 1.59,
        family: "Rutaceae",
        vitamin: ["Vitamin C", "Vitamin E"],
        color: ["yellow"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Lemons are bright yellow citrus fruits from the Rutaceae family, known for their sour taste and high vitamin C content. They are widely used in cooking and beverages.",
    },
    {
        name: "lime",
        price: 4.33,
        family: "Rutaceae",
        vitamin: ["Vitamin D", "Vitamin A"],
        color: ["yellow", "green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Limes are small, green citrus fruits with a tart flavor. Belonging to the Rutaceae family, they are essential in many dishes and drinks for their zest and acidity.",
    },
    {
        name: "mango",
        price: 4.09,
        family: "Anacardiaceae",
        vitamin: ["Vitamin B", "Vitamin C"],
        color: ["yellow", "green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Mangoes are juicy, tropical fruits from the Anacardiaceae family. Their sweet, rich flesh is enjoyed fresh, in smoothies, or used in cooking and desserts.",
    },
    {
        name: "mangosteen",
        price: 3.9,
        family: "Clusiaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["purple"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Mangosteens are tropical fruits with a thick purple rind and juicy, white inner segments. Known as the 'queen of fruits,' they have a unique sweet-tart flavor.",
    },
    {
        name: "melon",
        price: 4.81,
        family: "Cucurbitaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Melon is a broad term that refers to various fruits belonging to the Gourd family, including cantaloupe, honeydew, and watermelon. Melons are characterized by their sweet, juicy flesh and refreshing taste.",
    },
    {
        name: "nectarine",
        price: 2.44,
        family: "Rosaceae",
        vitamin: ["Vitamin B", "Vitamin C"],
        color: ["yellow", "green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Nectarines are smooth-skinned relatives of peaches from the Rosaceae family. They have a juicy, sweet flavor and are often eaten fresh or used in desserts.",
    },
    {
        name: "orange",
        price: 4.98,
        family: "Rutaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["purple"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Oranges are citrus fruits from the Rutaceae family, valued for their juicy, sweet-tart segments. They are popular in juices, snacks, and desserts.",
    },
    {
        name: "papaya",
        price: 1.8,
        family: "Caricaceae",
        vitamin: ["Vitamin D", "Vitamin A"],
        color: ["red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Papayas are tropical fruits with sweet, orange-red flesh and black seeds. They come from the Caricaceae family and are often eaten fresh or used in smoothies.",
    },
    {
        name: "passion-fruit",
        price: 4.84,
        family: "Passifloraceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["pink"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Passion fruits are round, tropical fruits with a tough rind and aromatic, tangy pulp. They are commonly used in drinks, desserts, and sauces.",
    },
    {
        name: "pear",
        price: 4.19,
        family: "Rosaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["purple"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Pears are soft, juicy fruits with a sweet flavor and a grainy texture. From the Rosaceae family, they are eaten fresh, poached, or used in desserts.",
    },
    {
        name: "persimmon",
        price: 4.24,
        family: "Ebenaceae",
        vitamin: ["Vitamin C", "Vitamin E"],
        color: ["green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Persimmons are orange-red fruits with a sweet, honey-like flavor. From the Ebenaceae family, they can be eaten fresh or dried when fully ripe.",
    },
    {
        name: "pineapple",
        price: 4.43,
        family: "Bromeliaceae",
        vitamin: ["Vitamin B", "Vitamin K"],
        color: ["yellow"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Pineapples are tropical fruits from the Bromeliaceae family with spiky skin and sweet-tart yellow flesh. They are widely used in cooking and drinks.",
    },
    {
        name: "plum",
        price: 4.4,
        family: "Rosaceae",
        vitamin: ["Vitamin C", "Vitamin E"],
        color: ["pink"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Plums are juicy fruits from the Rosaceae family, with smooth skin and a sweet-tart taste. They are eaten fresh, dried as prunes, or used in cooking.",
    },
    {
        name: "raspberry",
        price: 3.97,
        family: "Rosaceae",
        vitamin: ["Vitamin A", "Vitamin C"],
        color: ["orange", "red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Raspberries are small, red fruits with a delicate, sweet-tart flavor. They are commonly used in desserts, jams, and health foods.",
    },
    {
        name: "rose-apple",
        price: 3.82,
        family: "Myrtaceae",
        vitamin: ["Vitamin D", "Vitamin A"],
        color: ["yellow", "green"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Rose apples are bell-shaped tropical fruits with a crisp texture and subtle floral taste. They belong to the Myrtaceae family and are often eaten fresh.",
    },
    {
        name: "strawberry",
        price: 4.29,
        family: "Rosaceae",
        vitamin: ["Vitamin B", "Vitamin C"],
        color: ["orange", "red"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Strawberries are sweet, red berries with a juicy texture and fragrant aroma. From the Rosaceae family, they are popular in desserts, salads, and preserves.",
    },
    {
        name: "watermelon",
        price: 2.67,
        family: "Cucurbitaceae",
        vitamin: ["Vitamin C", "Vitamin E"],
        color: ["pink"],
        inCart: false,
        favourite: false,
        quantity: 1,
        description:
            "Watermelons are large fruits from the Cucurbitaceae family with juicy, sweet, red or pink flesh. They are perfect for hydration and enjoyed fresh during summer.",
    },
];

export default fruits;
